# ROUND(AVG(DAILY_RENTAL_FEE), 1) AS AVERAGE_FEE를 뽑아줘 ~
SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
# CAR_RENTAL_COMPANY_CAR 테이블에서
FROM CAR_RENTAL_COMPANY_CAR
# CAR_TYPE = 'SUV'인
WHERE CAR_TYPE = 'SUV'