# SELECT *
# FROM (
#     SELECT ID 
#     FROM ECOLI_DATA
# ) AS L LEFT OUTER JOIN (
#     SELECT PARENT_ID
#     FROM ECOLI_DATA
# ) AS R ON L.ID = R.PARENT_ID
# GROUP BY ID

# ID	PARENT_ID
# 1	1
# 2	2
# 3	null
# 4	4
# 5	null
# 6	null

SELECT ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM (
    SELECT ID 
    FROM ECOLI_DATA
) AS L LEFT OUTER JOIN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
) AS R ON L.ID = R.PARENT_ID
GROUP BY ID
