# 판매 날짜, 상품ID, 유저ID, 판매량
# SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT

# ALTER => 풀이상 DENIED
/*
ALTER TABLE OFFLINE_SALE ADD
(
    USER_ID	INTEGER
);
*/

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM (
        SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
            FROM ONLINE_SALE
                WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
        UNION ALL
        SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
            FROM OFFLINE_SALE
                WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
    ) AS CONCAT #Every derived table must have its own alias
        ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC