SELECT LL.CAR_ID AS CAR_ID, LL.CAR_TYPE AS CAR_TYPE, CAST(LL.FEE AS SIGNED) AS FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
        AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
        AND C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30 >= 500000
        AND C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30 < 2000000
        AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE H.CAR_ID = C.CAR_ID
                AND NOT (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30')
        )
) AS LL
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
