# 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
# REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
# TABLE => REST_INFO 일대다 REST_REVIEW => KEY = REST_ID

# REST_REVIEW 테이블에서 AVG(REVIEW_SCORE) 구하기 for 서브 쿼리
/*
SELECT REST_ID, AVG(REVIEW_SCORE) AS REVIEW_SCORE 
FROM REST_REVIEW
GROUP BY REST_ID
*/

SELECT L.REST_ID, L.REST_NAME, L.FOOD_TYPE, L.FAVORITES, L.ADDRESS, R.AVG_REVIEW_SCORE AS SCORE
    FROM REST_INFO L 
        JOIN (
            SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVG_REVIEW_SCORE 
            FROM REST_REVIEW
            GROUP BY REST_ID
        ) R ON L.REST_ID = R.REST_ID
        WHERE L.ADDRESS LIKE '서울%'
        ORDER BY SCORE DESC, L.FAVORITES DESC
# 맞는데...


