# FACTORY_ID, FACTORY_NAME, ADDRESS를 뽑아줘 ~
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
# FOOD_FACTORY 테이블에서
FROM FOOD_FACTORY
# ADDRESS가 강원도를 포함하는
WHERE ADDRESS LIKE '%강원도%'
# FACTORY_ID를 기준으로 ASC
ORDER BY FACTORY_ID ASC