# PT_NAME, PT_NO, GEND_CD, AGE, TLNO(NULL이면 NONE으로 처리)를 뽑아라
SELECT  PT_NAME, PT_NO, GEND_CD, AGE, ifnull(TLNO,'NONE')as TLNO
# PATIENT 테이블에서
FROM PATIENT
# AGE가 12이하이고 여자인 레코드만 골라서
WHERE (AGE <= 12) AND (GEND_CD = 'W')
# AGE 기준 DESC, PT_NAME 기준 ASC
ORDER BY AGE DESC, PT_NAME ASC