# DR_NAME, DR_ID, MCDP_CD, HIRE_YMD(DATE_FORMAT('%Y-%m-%d'))를 뽑아줘 ~
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
# DOCTOR 테이블에서
FROM DOCTOR
# MCDP_CD가 CS이거나 GS인 레코드만
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
# 1. HIRE_YMD을 기준으로 DESC
# 2. DR_NAME을 기준으로 ASC
ORDER BY HIRE_YMD DESC, DR_NAME ASC