# MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH(데이터포맷을 조정해서)를 뽑아라 
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
# MEMBER_PROFILE 테이블에서
FROM MEMBER_PROFILE 
# TLNO가 NULL이 아닌 레코드
# 그리고 DATE_OF_BIRTH가 3월인
# 그리고 GENDER가 W인
WHERE TLNO IS NOT NULL 
AND MONTH(DATE_OF_BIRTH) = 3
AND GENDER = 'W'
# MEMBER_ID를 기준으로 ASC
ORDER BY MEMBER_ID ASC