# RARITY = 'RARE'인 아이템의 ID
/*
SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE'
*/

# RARITY = 'RARE'인 아이템과 다음 아이템의 ID
/*
SELECT L.PARENT_ITEM_ID AS PARENT_ITEM_ID, L.ITEM_ID AS CHILD_ITEM_ID
    FROM ITEM_TREE L
        JOIN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') R
            ON L.PARENT_ITEM_ID = R.ITEM_ID
*/

# CHILD_ITEM_ID의 RARITY,아이템 ID를 기준으로 내림차순
SELECT R.ITEM_ID AS ITEM_ID, R.ITEM_NAME AS ITEM_NAME , R.RARITY AS RARITY
    FROM (SELECT L.PARENT_ITEM_ID AS PARENT_ITEM_ID, L.ITEM_ID AS CHILD_ITEM_ID
                FROM ITEM_TREE L
                    JOIN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') R
                        ON L.PARENT_ITEM_ID = R.ITEM_ID) L
        JOIN ITEM_INFO R
            ON L.CHILD_ITEM_ID = R.ITEM_ID
        ORDER BY ITEM_ID DESC
        