# DEVELOPERS 테이블에서 Python이나 C# 스킬을 가진 개발자의 정보를 조회

# CONV(바꿀 대상, 바꿀 대상의 진법, 변환 진법)
# CAST(바꿀 대상 AS 바꿀 자료형)

# DEVELOPERS 테이블의 SKILL_CODE를 이진수로 바꾸기 => CONV() 함수 이용
/*
SELECT CONV(SKILL_CODE, 10, 2) AS CONVERTED_CODE FROM DEVELOPERS
*/

# SKILLCODES의 CODE를 이진수로 바꾸기
/*
SELECT NAME, CONV(CODE, 10, 2) AS CONVERTED_CODE FROM SKILLCODES
*/
# Python	100000000
# C#	10000000000

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
    FROM DEVELOPERS
        WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0 
            OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
        ORDER BY ID ASC

# Python의 코드
# SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
# C#의 코드
# SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'