
SELECT 
    CAST(L.YEAR AS UNSIGNED) AS YEAR, 
    (R.MAX_SOC - L.SIZE_OF_COLONY) AS YEAR_DEV, 
    L.ID AS ID
FROM (
    SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR, SIZE_OF_COLONY, ID
    FROM ECOLI_DATA
) AS L JOIN (
    SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SOC
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS R ON L.YEAR = R.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC