# ICECREAM_INFO.FLAVOR를 뽑아줘 ~
SELECT ICECREAM_INFO.FLAVOR
# ICECREAM_INFO와 FIRST_HALF를 FLAVOR를 기준으로 JOIN한 테이블에서 
FROM (ICECREAM_INFO JOIN FIRST_HALF ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR)
# ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'인
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
# 그리고 FIRST_HALF.TOTAL_ORDER > 3000인
AND FIRST_HALF.TOTAL_ORDER > 3000;