SELECT LL.ID AS ID, RR.FISH_NAME AS FISH_NAME, LL.LENGTH AS LENGTH
FROM (
    SELECT L.ID AS ID, L.FISH_TYPE AS FISH_TYPE, L.LENGTH AS LENGTH
    FROM FISH_INFO AS L JOIN(
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        WHERE LENGTH > 10
        GROUP BY FISH_TYPE
    ) AS R ON L.FISH_TYPE = R.FISH_TYPE AND L.LENGTH = R.LENGTH
) AS LL JOIN FISH_NAME_INFO AS RR ON LL.FISH_TYPE = RR.FISH_TYPE
