SELECT L.TITLE, L.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD L
LEFT OUTER JOIN USED_GOODS_REPLY R ON L.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(L.CREATED_DATE, '%Y-%m') = '2022-10'
AND R.BOARD_ID IS NOT NULL
ORDER BY R.CREATED_DATE ASC, L.TITLE ASC